package app.naviamp.android.playback

object AndroidAutoPlaybackControls {
    const val MediaIdRoot = "naviamp.root"
    const val MediaIdNowPlaying = "naviamp.now_playing"
    const val MediaIdQueue = "naviamp.queue"
    const val MediaIdHome = "naviamp.home"
    const val MediaIdHomeMixes = "naviamp.home.mixes"
    const val MediaIdHomeRecentPlays = "naviamp.home.recent_plays"
    const val MediaIdHomeRecentlyAdded = "naviamp.home.recently_added"
    const val MediaIdLibrary = "naviamp.library"
    const val MediaIdLibraryArtists = "naviamp.library.artists"
    const val MediaIdLibraryAlbums = "naviamp.library.albums"
    const val MediaIdLibraryTracks = "naviamp.library.tracks"
    const val MediaIdCharts = "naviamp.charts"
    const val MediaIdChartsArtists = "naviamp.charts.artists"
    const val MediaIdChartsAlbums = "naviamp.charts.albums"
    const val MediaIdChartsTracks = "naviamp.charts.tracks"
    const val MediaIdRadio = "naviamp.radio"
    const val MediaIdRadioLibrary = "naviamp.radio.library"
    const val MediaIdRadioStations = "naviamp.radio.stations"
    const val MediaIdRadioRecent = "naviamp.radio.recent"
    const val MediaIdDownloads = "naviamp.downloads"
    const val MediaIdMore = "naviamp.more"
    const val MediaIdPlaylists = "naviamp.playlists"

    const val MediaIdArtistPrefix = "naviamp.artist:"
    const val MediaIdArtistGroupPrefix = "naviamp.artist.group:"
    const val MediaIdArtistTrackPrefix = "naviamp.artist.track:"
    const val MediaIdArtistShufflePrefix = "naviamp.artist.shuffle:"
    const val MediaIdAlbumPrefix = "naviamp.album:"
    const val MediaIdTrackPrefix = "naviamp.track:"
    const val MediaIdAlbumTrackPrefix = "naviamp.album.track:"
    const val MediaIdAlbumShufflePrefix = "naviamp.album.shuffle:"
    const val MediaIdQueueTrackPrefix = "naviamp.queue.track:"
    const val MediaIdDownloadPrefix = "naviamp.download:"
    const val MediaIdPlaylistPrefix = "naviamp.playlist:"
    const val MediaIdPlaylistTrackPrefix = "naviamp.playlist.track:"
    const val MediaIdRadioStationPrefix = "naviamp.radio.station:"
    const val MediaIdRecentRadioPrefix = "naviamp.radio.recent:"

    const val CommandPlayPause = "play_pause"
    const val CommandPrevious = "previous"
    const val CommandNext = "next"
}
