package app.naviamp.desktop

import androidx.compose.foundation.layout.Box
import androidx.compose.runtime.Composable
import androidx.compose.ui.Modifier
import app.naviamp.domain.InternetRadioStation
import app.naviamp.domain.Lyrics
import app.naviamp.domain.StreamQuality
import app.naviamp.domain.Track
import app.naviamp.domain.audio.AudioTag
import app.naviamp.domain.playback.PlaybackProgress
import app.naviamp.domain.playback.PlaybackState
import app.naviamp.domain.playback.PlaybackStreamMetadata
import app.naviamp.domain.playback.PlaybackVisualizerFrame
import app.naviamp.domain.playback.SleepTimerRequest
import app.naviamp.domain.queue.PlaybackQueue
import app.naviamp.domain.queue.RepeatMode
import app.naviamp.domain.waveform.AudioWaveform
import app.naviamp.ui.NaviampPlayerColors
import app.naviamp.ui.NaviampSleepTimerUi
import app.naviamp.ui.NaviampVisualizer

@Composable
internal fun DesktopNowPlayingRoute(
    modifier: Modifier = Modifier,
    appColors: DesktopAppColors,
    playbackEngineName: String,
    supportsPause: Boolean,
    supportsSoftwareVolume: Boolean,
    supportsTrackFavorites: Boolean,
    supportsTrackRatings: Boolean,
    nowPlayingTrack: Track?,
    nowPlayingWaveform: AudioWaveform?,
    visualizerFrame: PlaybackVisualizerFrame?,
    selectedVisualizer: NaviampVisualizer,
    visualizerColors: NaviampPlayerColors,
    nowPlayingAudioTags: List<AudioTag>?,
    nowPlayingLyrics: Lyrics?,
    nowPlayingLyricsStatus: String?,
    nowPlayingStreamMetadata: PlaybackStreamMetadata,
    lyricsVisible: Boolean,
    visualizerAvailable: Boolean,
    visualizerVisible: Boolean,
    coverArtUrl: String?,
    playbackQueue: PlaybackQueue,
    internetRadioStations: List<InternetRadioStation>,
    currentInternetRadioStationId: String?,
    radioTrackArtworkByKey: Map<String, String?>,
    relatedTracks: List<Track>,
    coverArtUrlForTrack: (Track) -> String?,
    hasPrevious: Boolean,
    hasNext: Boolean,
    shuffleActive: Boolean,
    repeatMode: RepeatMode,
    playbackState: PlaybackState,
    playbackProgress: PlaybackProgress,
    volumePercent: Int,
    sleepTimer: NaviampSleepTimerUi,
    streamQuality: StreamQuality,
    supportsSeek: Boolean,
    onPause: () -> Unit,
    onResume: () -> Unit,
    onPlayCurrent: () -> Unit,
    onSeek: (Double) -> Unit,
    onPrevious: () -> Unit,
    onNext: () -> Unit,
    onToggleShuffle: () -> Unit,
    onCycleRepeatMode: () -> Unit,
    onVolumeChanged: (Int) -> Unit,
    onToggleLyrics: () -> Unit,
    onLyricsOffsetChanged: (Int) -> Unit,
    onToggleVisualizer: () -> Unit,
    onVisualizerSelected: (NaviampVisualizer) -> Unit,
    onToggleTrackFavorite: (Track) -> Unit,
    onTrackRatingSelected: (Track, Int?) -> Unit,
    onArtistSelected: (Track) -> Unit,
    onAlbumSelected: (Track) -> Unit,
    onTrackRadioSelected: (Track) -> Unit,
    onDownloadTrackSelected: (Track) -> Unit,
    onAddTrackToPlaylist: (Track) -> Unit,
    onSaveQueueAsPlaylist: (String) -> Unit,
    onSleepTimerSelected: (SleepTimerRequest) -> Unit,
    onCancelSleepTimer: () -> Unit,
    onInternetRadioStationSelected: (InternetRadioStation) -> Unit,
    onQueueIndexSelected: (Int) -> Unit,
    onUpNextTrackRadioSelected: (Track) -> Unit,
    onUpNextTrackDownloadSelected: (Track) -> Unit,
    onUpNextTrackAddToPlaylist: (Track) -> Unit,
    onRelatedTrackSelected: (Int) -> Unit,
    onRelatedTrackPlayNext: (Track) -> Unit,
    onRelatedTrackAddToQueue: (Track) -> Unit,
    onRelatedTrackRadioSelected: (Track) -> Unit,
    onRelatedTrackDownloadSelected: (Track) -> Unit,
    onRelatedTrackAddToPlaylist: (Track) -> Unit,
    onCollapseToHome: () -> Unit,
) {
    Box(
        modifier = modifier,
    ) {
        DesktopNowPlayingPanel(
            appColors = appColors,
            playbackEngineName = playbackEngineName,
            supportsPause = supportsPause,
            supportsSoftwareVolume = supportsSoftwareVolume,
            supportsTrackFavorites = supportsTrackFavorites,
            supportsTrackRatings = supportsTrackRatings,
            nowPlayingTrack = nowPlayingTrack,
            nowPlayingWaveform = nowPlayingWaveform,
            visualizerBandsProvider = { visualizerFrame?.bands.orEmpty() },
            selectedVisualizer = selectedVisualizer,
            visualizerColors = visualizerColors,
            nowPlayingAudioTags = nowPlayingAudioTags,
            nowPlayingLyrics = nowPlayingLyrics,
            nowPlayingLyricsStatus = nowPlayingLyricsStatus,
            nowPlayingStreamMetadata = nowPlayingStreamMetadata,
            lyricsVisible = lyricsVisible,
            visualizerAvailable = visualizerAvailable,
            visualizerVisible = visualizerVisible,
            coverArtUrl = coverArtUrl,
            backTo = playbackQueue.backTo(),
            upNext = playbackQueue.upNext(),
            internetRadioStations = internetRadioStations,
            currentInternetRadioStationId = currentInternetRadioStationId,
            radioTrackArtworkByKey = radioTrackArtworkByKey,
            firstBackToQueueIndex = playbackQueue.currentIndex - 1,
            firstUpNextQueueIndex = playbackQueue.currentIndex + 1,
            upNextCoverArtUrl = coverArtUrlForTrack,
            relatedTracks = relatedTracks,
            relatedCoverArtUrl = coverArtUrlForTrack,
            hasPrevious = hasPrevious,
            hasNext = hasNext,
            shuffleEnabled = playbackQueue.upNext().size > 1,
            shuffleActive = shuffleActive,
            repeatMode = repeatMode,
            playbackState = playbackState,
            playbackProgress = playbackProgress,
            volumePercent = volumePercent,
            sleepTimer = sleepTimer,
            streamQuality = streamQuality,
            supportsSeek = supportsSeek,
            onPause = onPause,
            onResume = onResume,
            onPlayCurrent = onPlayCurrent,
            onSeek = onSeek,
            onPrevious = onPrevious,
            onNext = onNext,
            onToggleShuffle = onToggleShuffle,
            onCycleRepeatMode = onCycleRepeatMode,
            onVolumeChanged = onVolumeChanged,
            onToggleLyrics = onToggleLyrics,
            onLyricsOffsetChanged = onLyricsOffsetChanged,
            onToggleVisualizer = onToggleVisualizer,
            onVisualizerSelected = onVisualizerSelected,
            onToggleTrackFavorite = onToggleTrackFavorite,
            onTrackRatingSelected = onTrackRatingSelected,
            onArtistSelected = onArtistSelected,
            onAlbumSelected = onAlbumSelected,
            onTrackRadioSelected = onTrackRadioSelected,
            onDownloadTrackSelected = onDownloadTrackSelected,
            onAddTrackToPlaylist = onAddTrackToPlaylist,
            onSaveQueueAsPlaylist = onSaveQueueAsPlaylist,
            onSleepTimerSelected = onSleepTimerSelected,
            onCancelSleepTimer = onCancelSleepTimer,
            onInternetRadioStationSelected = onInternetRadioStationSelected,
            onQueueIndexSelected = onQueueIndexSelected,
            onUpNextTrackRadioSelected = onUpNextTrackRadioSelected,
            onUpNextTrackDownloadSelected = onUpNextTrackDownloadSelected,
            onUpNextTrackAddToPlaylist = onUpNextTrackAddToPlaylist,
            onRelatedTrackSelected = onRelatedTrackSelected,
            onRelatedTrackPlayNext = onRelatedTrackPlayNext,
            onRelatedTrackAddToQueue = onRelatedTrackAddToQueue,
            onRelatedTrackRadioSelected = onRelatedTrackRadioSelected,
            onRelatedTrackDownloadSelected = onRelatedTrackDownloadSelected,
            onRelatedTrackAddToPlaylist = onRelatedTrackAddToPlaylist,
            onCollapseToHome = onCollapseToHome,
        )
    }
}
