package app.naviamp.android

import app.naviamp.android.playback.AndroidPlaybackEngine
import app.naviamp.domain.playback.SleepTimerController
import kotlinx.coroutines.CoroutineScope

internal fun androidMainShellActions(
    scope: CoroutineScope,
    state: AndroidAppState,
    storage: AndroidStorageDependencies,
    playbackEngine: AndroidPlaybackEngine,
    settingsStore: AndroidSettingsStore,
    searchController: AndroidSearchController,
    mediaAppController: AndroidMediaAppController,
    playbackAppController: AndroidPlaybackAppController,
    navigationController: AndroidNavigationController,
    artistActionController: AndroidArtistActionController,
    mixBuilderController: AndroidMixBuilderController,
    playlistActionController: AndroidPlaylistActionController,
    sleepTimerController: SleepTimerController,
    downloadActionController: AndroidDownloadActionController,
    settingsMaintenanceController: AndroidSettingsMaintenanceController,
    connectionSessionController: AndroidConnectionSessionController,
    shellPlaybackController: AndroidShellPlaybackController,
    shellMediaController: AndroidShellMediaController,
    trackActionController: AndroidTrackActionController,
    sonicPathController: AndroidSonicPathController,
    sonicMixController: AndroidSonicMixController,
    sonicHomeDiscoveryController: AndroidSonicHomeDiscoveryController,
    nowPlayingSidecarController: AndroidNowPlayingSidecarController,
): AndroidAppShellActions =
    androidAppShellActions(
        state = state,
        playbackEngine = playbackEngine,
        settingsStore = settingsStore,
        handleConnectionFormChanged = settingsMaintenanceController::handleConnectionFormChanged,
        connectToNavidrome = connectionSessionController::connectToNavidrome,
        handlePlaybackSettingsChanged = settingsMaintenanceController::handlePlaybackSettingsChanged,
        handlePlaybackSettingsChangedAndRedownload = settingsMaintenanceController::handlePlaybackSettingsChangedAndRedownload,
        handleCacheSettingsChanged = settingsMaintenanceController::handleCacheSettingsChanged,
        handleClearCache = settingsMaintenanceController::handleClearCache,
        handleClearLibrary = settingsMaintenanceController::handleClearLibrary,
        handleResetDatabase = settingsMaintenanceController::handleResetDatabase,
        handleSearch = { searchController.launchSearch(scope) },
        handleArtistMixSearch = mixBuilderController::searchArtistSuggestions,
        handleArtistMixArtistSelected = { item -> mixBuilderController.selectArtistByItemId(item.id) },
        handleArtistMixArtistRemoved = { item -> mixBuilderController.removeArtistByItemId(item.id) },
        handleArtistMixReset = mixBuilderController::resetArtistBuilder,
        handleArtistMixPlay = mixBuilderController::playArtistMix,
        handleAlbumMixSearch = mixBuilderController::searchAlbumSuggestions,
        handleAlbumMixAlbumSelected = { item -> mixBuilderController.selectAlbumByItemId(item.id) },
        handleAlbumMixAlbumRemoved = { item -> mixBuilderController.removeAlbumByItemId(item.id) },
        handleAlbumMixReset = mixBuilderController::resetAlbumBuilder,
        handleAlbumMixPlay = mixBuilderController::playAlbumMix,
        handleGenreMixSearch = mixBuilderController::refreshGenreSuggestions,
        handleGenreMixGenreSelected = { item -> mixBuilderController.selectGenreByItemId(item.id) },
        handleGenreMixGenreRemoved = { item -> mixBuilderController.removeGenreByItemId(item.id) },
        handleGenreMixReset = mixBuilderController::resetGenreBuilder,
        handleGenreMixPlay = mixBuilderController::playGenreMix,
        handleSonicPathStartQueryChanged = sonicPathController::updateStartQuery,
        handleSonicPathEndQueryChanged = sonicPathController::updateEndQuery,
        handleSonicPathStartSearch = sonicPathController::searchStartTracks,
        handleSonicPathEndSearch = sonicPathController::searchEndTracks,
        handleSonicPathStartTrackSelected = sonicPathController::selectStartTrack,
        handleSonicPathEndTrackSelected = sonicPathController::selectEndTrack,
        handleSonicPathStartTrackCleared = sonicPathController::clearStartTrack,
        handleSonicPathEndTrackCleared = sonicPathController::clearEndTrack,
        handleSonicPathCountChanged = sonicPathController::updateCount,
        handleSonicPathBuild = sonicPathController::buildPath,
        handleSonicPathReset = sonicPathController::reset,
        handleSonicPathPlay = sonicPathController::playPath,
        handleSonicPathAddToQueue = sonicPathController::addPathToQueue,
        handleSonicPathSaveAsPlaylist = { name ->
            playlistActionController.saveTracksAsPlaylist(name, sonicPathController.playlistTracks(), "sonic path")
        },
        handleSonicMixQueryChanged = sonicMixController::updateQuery,
        handleSonicMixSearch = sonicMixController::searchTracks,
        handleSonicMixTrackSelected = sonicMixController::selectTrack,
        handleSonicMixTrackRemoved = sonicMixController::removeTrack,
        handleSonicMixTargetLengthChanged = sonicMixController::updateTargetLength,
        handleSonicMixBiasChanged = sonicMixController::updateBias,
        handleSonicMixBuild = sonicMixController::buildMix,
        handleSonicMixReset = sonicMixController::reset,
        handleSonicMixPlay = sonicMixController::playMix,
        handleSonicMixAddToQueue = sonicMixController::addMixToQueue,
        handleSonicMixSaveAsPlaylist = { name ->
            playlistActionController.saveTracksAsPlaylist(name, sonicMixController.playlistTracks(), "sonic mix")
        },
        startAndroidLibrarySync = { force -> startAndroidLibrarySync(scope, state, storage, force) },
        handleShellTrackSelected = shellMediaController::handleShellTrackSelected,
        handleDownloadedTrackAction = trackActionController::handleDownloadedTrackAction,
        handleShellAlbumSelected = shellMediaController::handleShellAlbumSelected,
        handleAlbumFavoriteToggled = { item -> toggleAndroidAlbumFavorite(scope, state, item, storage) },
        handleMixAlbumSelected = shellMediaController::handleMixAlbumSelected,
        handleShellAlbumPlay = shellMediaController::handleShellAlbumPlay,
        handleShellAlbumTrackSelected = shellMediaController::handleShellAlbumTrackSelected,
        handleShellAlbumRadio = shellMediaController::handleShellAlbumRadio,
        appendTracksToQueue = mediaAppController::appendTracksToQueue,
        downloadTracks = downloadActionController::downloadTracks,
        addTracksToPlaylist = playlistActionController::addTracksToPlaylist,
        handleTrackAction = trackActionController::handleTrackAction,
        handleShellArtistRadio = artistActionController::handleShellArtistRadio,
        handleShellArtistShuffle = artistActionController::handleShellArtistShuffle,
        loadArtistTracks = artistActionController::loadArtistTracks,
        handleArtistPopularPlay = artistActionController::handleArtistPopularPlay,
        handleShellArtistPopularRadio = artistActionController::handleShellArtistPopularRadio,
        handleArtistPopularTrackSelected = artistActionController::handleArtistPopularTrackSelected,
        handleArtistPopularAddToQueue = artistActionController::handleArtistPopularAddToQueue,
        findSimilarArtists = artistActionController::findSimilarArtists,
        handleSimilarArtistSelected = artistActionController::handleSimilarArtistSelected,
        openExternalArtistUrl = artistActionController::openExternalArtistUrl,
        openArtistDetails = { artistId, fallbackName ->
            mediaAppController.openArtistDetails(artistId, fallbackName)
        },
        handleArtistFavoriteToggled = { item -> toggleAndroidArtistFavorite(scope, state, item, storage) },
        handleArtistAlbumRadio = artistActionController::handleArtistAlbumRadio,
        loadArtistAlbumTracks = artistActionController::loadArtistAlbumTracks,
        openPlaylistDetails = playlistActionController::openPlaylistDetails,
        playPlaylist = playlistActionController::playPlaylist,
        downloadPlaylist = downloadActionController::downloadPlaylist,
        addPlaylistToQueue = playlistActionController::addPlaylistToQueue,
        addPlaylistToPlaylist = playlistActionController::addPlaylistToPlaylist,
        renamePlaylist = playlistActionController::renamePlaylist,
        deletePlaylist = playlistActionController::deletePlaylist,
        saveSmartPlaylist = playlistActionController::saveSmartPlaylist,
        updateSmartPlaylist = playlistActionController::updateSmartPlaylist,
        loadSmartPlaylist = playlistActionController::loadSmartPlaylistDefinition,
        closeActivePlaylist = navigationController::closeActivePlaylist,
        handlePlaylistTrackSelected = trackActionController::handlePlaylistTrackSelected,
        handleRecentRadioSelected = shellMediaController::handleShellRecentRadioSelected,
        handleMixBuilderSelected = navigationController::handleMixBuilderSelected,
        handleRadioStationSelected = shellMediaController::handleRadioStationSelected,
        saveInternetRadioStation = shellMediaController::saveInternetRadioStation,
        deleteInternetRadioStation = shellMediaController::deleteInternetRadioStation,
        handleShellHomeStationSelected = shellMediaController::handleShellHomeStationSelected,
        handleSonicDiscoveryTrackAction = sonicHomeDiscoveryController::handleAction,
        closeActiveDetail = navigationController::closeActiveDetail,
        handleShellResume = shellPlaybackController::resume,
        playAdjacentTrack = playbackAppController::playAdjacentTrack,
        performSeek = playbackAppController::performSeek,
        handleShellToggleShuffle = shellPlaybackController::toggleShuffle,
        loadLyrics = nowPlayingSidecarController::loadLyrics,
        handleLyricsOffsetChanged = nowPlayingSidecarController::handleLyricsOffsetChanged,
        handleShellTrackRadio = shellPlaybackController::startCurrentTrackRadio,
        handleNowPlayingAddToPlaylist = trackActionController::handleNowPlayingAddToPlaylist,
        handleNowPlayingCreatePlaylistAndAdd = trackActionController::handleNowPlayingCreatePlaylistAndAdd,
        handleSaveQueueAsPlaylist = playlistActionController::saveQueueAsPlaylist,
        handleSleepTimerSelected = sleepTimerController::select,
        handleCancelSleepTimer = sleepTimerController::cancel,
        downloadTrack = downloadActionController::downloadTrack,
        handleShellGoToAlbum = shellMediaController::handleShellGoToAlbum,
        handleShellGoToArtist = shellMediaController::handleShellGoToArtist,
        handleShellQueueItemRadio = shellPlaybackController::startQueueItemRadio,
        handleQueueItemPlayNext = { item ->
            mediaAppController.resolveNowPlayingItemTrack(item)?.let(mediaAppController::playNext)
        },
        handleQueueItemAddToQueue = { item ->
            mediaAppController.resolveNowPlayingItemTrack(item)?.let(mediaAppController::addToQueue)
        },
        handleQueueItemRemoveFromQueue = mediaAppController::removeFromQueue,
        handleEmptyQueue = mediaAppController::emptyQueue,
        handleTrackRadioNext = trackActionController::playTrackRadioNext,
        handleAddTrackRadioToQueue = trackActionController::addTrackRadioToQueue,
        resolveNowPlayingItemTrack = mediaAppController::resolveNowPlayingItemTrack,
        addTrackToPlaylist = playlistActionController::addTrackToPlaylist,
        toggleCurrentFavorite = mediaAppController::toggleCurrentFavorite,
        handleShellRatingSelected = shellMediaController::handleShellRatingSelected,
    )
