package app.naviamp.android

import androidx.compose.runtime.Composable
import app.naviamp.ui.NaviampCacheSettingsUi
import app.naviamp.ui.NaviampSharedAppShell
import app.naviamp.ui.settingsSyncUi
import app.naviamp.ui.toConnectionSettingsUi
import app.naviamp.ui.toGeneralSettingsUi
import app.naviamp.ui.toPlaybackSettingsUi

@Composable
fun AndroidAppShellContent(
    state: AndroidAppShellUiState,
    actions: AndroidAppShellActions,
    settingsSyncStatus: String? = null,
    onImportSettingsSyncFile: (() -> Unit)? = null,
    onChooseSettingsSyncFolder: (() -> Unit)? = null,
    onImportSettingsSyncFolder: (() -> Unit)? = null,
    onExportSettingsSyncFolder: (() -> Unit)? = null,
    settingsSyncAutoExportEnabled: Boolean = false,
    onSettingsSyncAutoExportChanged: ((Boolean) -> Unit)? = null,
) {
    NaviampSharedAppShell(
        modifier = state.modifier,
        connectionSettings = state.connection.toConnectionSettingsUi(state.capabilities),
        general = state.interfaceSettings.toGeneralSettingsUi(state.about),
        playback = state.playbackSettings.toPlaybackSettingsUi(
            capabilities = state.capabilities,
            downloadBytes = state.downloadBytes,
        ),
        cache = NaviampCacheSettingsUi(
            settings = state.cacheSettings,
            diagnostics = state.diagnostics,
            fileSelectionAvailable = state.capabilities.fileSelection,
            downloadLocations = state.downloadLocations,
            audioCacheLocations = state.audioCacheLocations,
            selectedDownloadLocationId = state.selectedDownloadLocationId,
            selectedAudioCacheLocationId = state.selectedAudioCacheLocationId,
        ),
        settingsSync = settingsSyncUi(
            directoryPath = null,
            autoExportEnabled = settingsSyncAutoExportEnabled,
            status = settingsSyncStatus,
            capabilities = state.capabilities,
        ),
        supportsDownloads = state.capabilities.downloads,
        supportsApplicationUpdates = state.capabilities.applicationUpdates,
        selectedVisualizer = state.selectedVisualizer,
        visualizerBandsProvider = state.visualizerBandsProvider,
        query = state.search.query,
        home = state.home,
        homeRefreshing = state.homeRefreshing,
        searchResults = state.search.results,
        artistMixBuilder = state.artistMixBuilder,
        albumMixBuilder = state.albumMixBuilder,
        genreMixBuilder = state.genreMixBuilder,
        sonicPathBuilder = state.sonicPathBuilder,
        sonicMixBuilder = state.sonicMixBuilder,
        libraryArtists = state.library.artists,
        libraryQuery = state.library.query,
        librarySyncStatus = state.library.syncStatus,
        downloads = state.downloads,
        downloadBytes = state.downloadBytes,
        maxDownloadBytes = state.maxDownloadBytes,
        offlineDashboard = state.offlineDashboard,
        downloadStatus = state.downloadStatus,
        downloadJobs = state.downloadJobs,
        keepFavoritesDownloaded = state.keepFavoritesDownloaded,
        playlistItems = state.playlistItems,
        recentPlaylistIds = state.recentPlaylistIds,
        playlistSortMode = state.playlistSortMode,
        playlistChoices = state.playlistChoices,
        playlistActionStatus = state.playlistActionStatus,
        playlistRefreshing = state.playlistRefreshing,
        radioStations = state.radioStations,
        radioRefreshing = state.radioRefreshing,
        albumDetail = state.albumDetail,
        artistDetail = state.artistDetail,
        playlistDetail = state.playlistDetail,
        nowPlaying = state.nowPlaying,
        nowPlayingOpen = state.nowPlayingOpen,
        selectedRoute = state.selectedRoute,
        onRouteSelected = actions.onRouteSelected,
        onConnectionFormChanged = actions.onConnectionFormChanged,
        onConnect = actions.onConnect,
        onEditConnection = actions.onEditConnection,
        onNewConnection = actions.onNewConnection,
        onEditSavedConnection = actions.onEditSavedConnection,
        onConnectSavedConnection = actions.onConnectSavedConnection,
        onDeleteSavedConnection = actions.onDeleteSavedConnection,
        onImportSettingsSyncFile = onImportSettingsSyncFile.takeIf {
            state.capabilities.settingsImportExport && state.capabilities.fileSelection
        },
        onChooseSettingsSyncFolder = onChooseSettingsSyncFolder.takeIf {
            state.capabilities.settingsImportExport && state.capabilities.fileSelection
        },
        onImportSettingsSyncFolder = onImportSettingsSyncFolder.takeIf {
            state.capabilities.settingsImportExport && state.capabilities.fileSelection
        },
        onExportSettingsSyncFolder = onExportSettingsSyncFolder.takeIf {
            state.capabilities.settingsImportExport && state.capabilities.fileSelection
        },
        onSettingsSyncAutoExportChanged = onSettingsSyncAutoExportChanged,
        onCancelEditConnection = actions.onCancelEditConnection,
        onInterfaceSettingsChanged = actions.onInterfaceSettingsChanged,
        onPlaybackSettingsChanged = actions.onPlaybackSettingsChanged,
        onPlaybackSettingsChangedAndRedownload = actions.onPlaybackSettingsChangedAndRedownload,
        onCacheSettingsChanged = actions.onCacheSettingsChanged,
        onDownloadLocationChanged = actions.onDownloadLocationChanged,
        onAudioCacheLocationChanged = actions.onAudioCacheLocationChanged,
        onClearCache = actions.onClearCache,
        onClearLibrary = actions.onClearLibrary,
        onResetDatabase = actions.onResetDatabase,
        onQueryChanged = actions.onQueryChanged,
        onSearch = actions.onSearch,
        onClearSearch = actions.onClearSearch,
        artistMixActions = actions.artistMixActions,
        albumMixActions = actions.albumMixActions,
        genreMixActions = actions.genreMixActions,
        sonicPathActions = actions.sonicPathActions,
        sonicMixActions = actions.sonicMixActions,
        onLibraryQueryChanged = actions.onLibraryQueryChanged,
        onRefreshHome = actions.onRefreshHome,
        onRefreshLibrary = actions.onRefreshLibrary,
        onLoadMoreLibrary = actions.onLoadMoreLibrary,
        onRefreshPlaylists = actions.onRefreshPlaylists,
        onRefreshRadioStations = actions.onRefreshRadioStations,
        onTrackSelected = actions.onTrackSelected,
        onDownloadedTrackAction = actions.onDownloadedTrackAction,
        onCancelDownloadJob = actions.onCancelDownloadJob,
        onRetryDownloadJob = actions.onRetryDownloadJob,
        onRefreshDownloads = actions.onRefreshDownloads,
        onToggleKeepFavoritesDownloaded = actions.onToggleKeepFavoritesDownloaded,
        onDeleteAllDownloads = actions.onDeleteAllDownloads,
        onAlbumSelected = actions.onAlbumSelected,
        onAlbumFavoriteToggled = actions.onAlbumFavoriteToggled,
        onMixAlbumSelected = actions.onMixAlbumSelected,
        onAlbumPlay = actions.onAlbumPlay,
        onAlbumTrackSelected = actions.onAlbumTrackSelected,
        onAlbumRadio = actions.onAlbumRadio,
        onAlbumAddToQueue = actions.onAlbumAddToQueue,
        onAlbumDownload = actions.onAlbumDownload,
        onAlbumAddToPlaylist = actions.onAlbumAddToPlaylist,
        onAlbumCreatePlaylistAndAdd = actions.onAlbumCreatePlaylistAndAdd,
        onTrackAction = actions.onTrackAction,
        onArtistRadio = actions.onArtistRadio,
        onArtistPlay = actions.onArtistPlay,
        onArtistShuffle = actions.onArtistShuffle,
        onArtistAddToQueue = actions.onArtistAddToQueue,
        onArtistAddToPlaylist = actions.onArtistAddToPlaylist,
        onArtistCreatePlaylistAndAdd = actions.onArtistCreatePlaylistAndAdd,
        onArtistPopularPlay = actions.onArtistPopularPlay,
        onArtistPopularRadio = actions.onArtistPopularRadio,
        onArtistPopularTrackSelected = actions.onArtistPopularTrackSelected,
        onArtistPopularAddToQueue = actions.onArtistPopularAddToQueue,
        onFindSimilarArtists = actions.onFindSimilarArtists,
        onSimilarArtistSelected = actions.onSimilarArtistSelected,
        onSimilarArtistExternalSelected = actions.onSimilarArtistExternalSelected,
        onArtistSelected = actions.onArtistSelected,
        onArtistFavoriteToggled = actions.onArtistFavoriteToggled,
        onPlaylistSelected = actions.onPlaylistSelected,
        onPlaylistSortModeChanged = actions.onPlaylistSortModeChanged,
        onPlaylistPlay = actions.onPlaylistPlay,
        onPlaylistAddToQueue = actions.onPlaylistAddToQueue,
        onPlaylistAddToPlaylist = actions.onPlaylistAddToPlaylist,
        onPlaylistCreatePlaylistAndAdd = actions.onPlaylistCreatePlaylistAndAdd,
        onPlaylistCopy = actions.onPlaylistCopy,
        onPlaylistRename = actions.onPlaylistRename,
        onPlaylistDelete = actions.onPlaylistDelete,
        onStandardPlaylistUpdate = actions.onStandardPlaylistUpdate,
        onMediaItemAction = actions.onMediaItemAction,
        onSmartPlaylistSave = actions.onSmartPlaylistSave,
        onSmartPlaylistUpdate = actions.onSmartPlaylistUpdate,
        onSmartPlaylistSaveWithPassword = actions.onSmartPlaylistSaveWithPassword,
        onSmartPlaylistUpdateWithPassword = actions.onSmartPlaylistUpdateWithPassword,
        onSmartPlaylistLoad = actions.onSmartPlaylistLoad,
        onPlaylistBack = actions.onPlaylistBack,
        onPlaylistTrackSelected = actions.onPlaylistTrackSelected,
        onRecentRadioSelected = actions.onRecentRadioSelected,
        onMixBuilderSelected = actions.onMixBuilderSelected,
        onRadioStationSelected = actions.onRadioStationSelected,
        onRadioStationSave = actions.onRadioStationSave,
        onStationAction = actions.onStationAction,
        onHomeStationSelected = actions.onHomeStationSelected,
        onSonicDiscoveryTrackAction = actions.onSonicDiscoveryTrackAction,
        onOpenNowPlaying = actions.onOpenNowPlaying,
        onCloseNowPlaying = actions.onCloseNowPlaying,
        onNowPlayingPlaybackAction = actions.onNowPlayingPlaybackAction,
        onNowPlayingDisplayAction = actions.onNowPlayingDisplayAction,
        onNowPlayingCurrentTrackAction = actions.onNowPlayingCurrentTrackAction,
        onNowPlayingQueueAction = actions.onNowPlayingQueueAction,
        onNowPlayingSleepTimerAction = actions.onNowPlayingSleepTimerAction,
        onNowPlayingSelectionAction = actions.onNowPlayingSelectionAction,
        onQueueItemAction = actions.onQueueItemAction,
    )
}
